# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-foss-license-checker"
BBFILE_PATTERN_meta-foss-license-checker = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-foss-license-checker = "6"

LAYERDEPENDS_meta-foss-license-checker = "core"
LAYERSERIES_COMPAT_meta-foss-license-checker = "scarthgap"

# Extend the insane.bbclass with FOSS License Checker Tool 
INHERIT += "insane-appended"

# Enable/disable the license check tool
ENABLE_LICENSE_CHECK_TOOL = "1"

# Turn on/off header file inclusion in FOSS License Checker Tool
INCLUDE_HEADERS = "1"

# Turn on/off inclusion of system header files in FOSS License Checker Tool
INCLUDE_BASE_HEADERS = "1"

# Stop stripping ELF in recipe-sysroot for symbol comparison purpose in FOSS License Checker Tool
INHIBIT_SYSROOT_STRIP = "1"

# Get path to layer workspace
LAYERDIR_WS = "${LAYERDIR}"


addpylib ${LAYERDIR}/src lib
